//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lilCommunity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public string MessageSubject { get; set; }
        public string MessageText { get; set; }
        public System.DateTime MessageTime { get; set; }
        public string UserId { get; set; }
        public bool MessageStatus { get; set; }
    }
}
